### ISSUE TITLE
Regarding https://smuth.me/post/powerdns-4-with-terraform/

### ISSUE THREAD

**Issue by gtmtech** [smuth4/smuth.me#1]
Hi, I saw your blog, (although there's no way to comment on your blog), so I raised an issue here if you are interested...

I am hitting this at the moment, but you might like to know...

The api endpoint has changed from / to /api/v1/, but the terraform powerdns provider has all the ability to cope with this, if you just specify e.g.

```
provider "powerdns" {
    server_url = "http://127.0.0.1:8081/api/v1"
}
```

in your terraform resource, it works just fine.

However, what does not seem to work fine, is the `ttl` field, because they've changed the location of it. If you were able to get the `ttl` working, it would be great to know about it - otherwise, I'm busy modifying the terraform provider to work with PowerDNS4.

**Comment by smuth4** [comment]
I actually already did work to fix the provider, I left some comments in https://github.com/hashicorp/terraform/issues/7790 about it. I'm going to close this ticket, but I'll keep communicating via the terraform issue.
